### ISSUE TITLE
handling genitive case (and maybe other cases too)

### ISSUE THREAD

**Issue by mikkokotila** [Esukhia/pybo#15]
It looks like right now the mode of operation is where the case particle འི་ is separated from the word it belongs to. For example སེམས་དཔའི  becomes སེམས་དཔ འི  which of course renders the word incomprehensible in a programmatic sense. Is there a reason to handle it this way by default? I understand there might be benefit for having it as an option though.

This discussion then goes on to all འབྲེལ་སྒྲ་ and maybe other cases as well? I did not look yet, but seeing how often ར་ comes up, I'm guessing ལ་དོན་ is handled in the same way? I guess at least with འབྲེལ་སྒྲ་ it's similar to having an english language NLP treating 's as a word as opposed to a modifier that belongs to the root word. Or am I missing something?

**Comment by mikkokotila** [comment]
So ok I understand ལ་དོན་ needs to be handled in the way it is handled at the moment...so the འབྲེལ་སྒྲ་ part remains.

**Comment by ngawangtrinley** [comment]
I'm not 100% sure I get your question but it seems to be about the affixed particles: the general tule is that words ending with the suffix འ such as ཀུན་དགའ་ drop the འ་ when getting a particle ཀུན་དགའི་, ཀུན་དགས་, ཀུན་དགར་, in contrast with no suffix words like ང་: ངའི་, ངས་, ངར་. So it's a bit different than the english 's.
The main problem this creates is that straight splitting creates new existing words like ཀུན་དག་(pure) or དགར་(to select). As a result Pybo's segmentation, lemma assignment, and affixed particle resolution is not perfect and needs adjustment by manual rules to start and hopefully models when we have more good data.

**Comment by drupchen** [comment]
If your main concern is that it renders the word incomprehensible, it is for that very reason that we have a lot of different attributes.
1. content: the raw substring corresponding to the current token
2. cleaned_content: the preprocessed syllables that are clean and neat syllables ending with a tsek
3. unaffixed_word: the cleaned_content turned into a comprehensible word by reinserting the འ when relevant
4. lemma: the canonical form of the current word. that is usually the form you find in dictionaries or the most representative case form.

For the genetive case, 
in 1, I expect to find the substring of the original together with any space or tseks
in 2, I expect to find the same characters as in the original, but without spaces or tseks (the pre-processed form, actually)
in 3, I expect to find the same thing as in 2 because there is no འ needed
in 4, I expect the comprehensible form of the genetive case, which here is subjectively chosen to be གི་

Instead of enforcing one behaviour that would only fit one need, I prefer to expose all those attributes for every token. This keeps the spirit of pybo to be a toolbox instead of an application that does only one thing. This flexibility also allows you to devise a treatment that will suit your needs, since you can also access the pos of the token, and if its content is `PART`, you can decide of extracting the lemma, and keep any other attribute for the rest of the tokens.

Note that the cleaned_content keeps track of the affixed particles in adding the tsek to the syllables, so in case you want to have the cleaned text and still have the particles affixed, you can do so by testing the following and concatenating it to the previous cleaned_content if true: 
- the pos of the token is `PART`
- the `affix` attribute is `True`
- the `affixed` attribute of the preceding token is `True`

If your need is still not catered, please give me a full example, and I will ensure it is possible to get what you want.

**Comment by drupchen** [comment]
ah ! and if you want to have a given string segmented, but still keeping the affixed particles within the same token, it is possible to do so by calling 
```
pybo.BoTokenizer('POS').tokenize(in_string, split_particles=False)
```
You would still have the lemma without the affixed particle in this case. Actually, splitting the affixed particles is an additional process after the actual tokenizing, so you can simply opt to not do it.

**Comment by mikkokotila** [comment]
Ok great, I tried split_affixed and that does the job! Also thanks for the background, that all makes sense 👍
