### ISSUE TITLE
Cache and reuse temporary files to speed up initialization

### ISSUE THREAD

**Issue by BLKSerene** [Esukhia/pybo#34]
When initializing `BoTokenizer`, `POS_trie.pickled` and `pybo.yaml` are generated into the working directory. Is it possible to cache these files so that there would be no need to re-generate them after the first initialization (I'm not sure whether this would speed up the initialization process though).

And I think that it would be better to store the temporary files in a fixed position (e.g. C:/Users/UserName/Documents on Windows), instead of the working directory.

Also, this would requires pybo to check whether the temporary files are generated by an older version of pybo (hence the need to update them even there already exists a cached version).

**Comment by drupchen** [comment]
The files are by default reused. That is the purpose of creating them in the first place. as for `pybo.yaml`, the file is meant to allow the user to override the default behavior by locally modifying it.

`pybo.yaml` being a config file, do you thing the best location will be the cache directory?

As for `XXX_trie.pickled`, we could include pybo's major and/or minor version in the filename. Then have the name parsed against the current version number. (I don't have much time right now to do that, but it shouldn't be very difficult to do)

Loading the pickled trie takes about 5s. or less on my machine, while creating the trie from scratch could take 15s. or more. So there is a real gain.

**Comment by BLKSerene** [comment]
If the config file is provided as a convenient way to modify the behavior of the tokenizer, then it makes sense to store it in the working directory (and I'm curious about what can be done with this file, since it's not documented?)

I'm using the tokenizer in my GUI-based program, during each session only one instance of BoTokenizer will be used in the program, but when user closes the program and restart a new session, a new instance must be created again, so I suppose there's no need to generate `POS_trie.pickled` the second time. (As you said, it take about 15 seconds to generate it from scratch).

And another issue:  `pybo.yaml` will also be updated every time a new instance of `BoTokenizer` is created, so won't the last changes the user has just made to this config file be overwritten by the default values?

**Comment by drupchen** [comment]
The config file is provided to enable to switch between tokenizer profiles, or create new ones that can then be used to create a custom trie. The default profiles are [here](https://github.com/Esukhia/pybo/blob/master/pybo/config.py#L30-L34). 
`pytib` is the smallest trie, and the cleanest of all. Which means that there will be lots of words it won't know about, and they will all be turned into syllables each considered a non-word.
It shouldn't be the case, but I see that for some reason, `pytib` and `POS` have the same content...
`GMD` stands for [Grand Monlam Dictionary](http://monlamit.com/node/156) see [this older version](https://github.com/iamironrabbit/monlam-dictionary)
This profile has a much larger coverage, but has also lots of entries that will be larger than the smallest possible word unit, since compounds of words are included in dictionaries. Overall, the best profile and the most generic is `GMD`.

Should you wish to create a trie without POS tags, you can create a new profile that copies GMD while omitting `*tibdict`, since that is where the POS tags come from. The trie will still be built and pybo won't complain it doesn't find the source for POS tags. So that way, you might have a clean trie without any POS tags.

The other part of the config file is [pipeline profiles](https://github.com/Esukhia/pybo/blob/master/pybo/config.py#L36). This is the latest addition to pybo and the documentation still hasn't been put together. but if you are courageous, check [here](https://github.com/Esukhia/bospell#usage) and the links to the other readmes. I adapted the code to pybo, but the idea is still the same.

By default, any existing pickled trie or config file will be used. In their absence, the trie will be built from scratch, and the config file will be written. So user changes won't be overwritten. So as long as your program doesn't delete the trie and the config file created on the first run, you will simply use them for all subsequent executions.

**Comment by BLKSerene** [comment]
Ah, I've just checked again, pybo do reuse the cached trie file after the first instantialization, I misunderstood.
So the only issue is to check against the version of the old cached trie file (to update it if needed), thanks for your detailed reply.

**Comment by drupchen** [comment]
I don't this this should be taken as an issue as pybo is built with the idea that the content of the trie will be improved by improving the lists of words. That is why there are tokenizer profiles. I don't think of ever shipping already pickled tries.

On the other hand, the implementation of tries won't change from one version of pybo to the next in the forseable future, making unnecessary to rebuild the trie just because there is a new pybo version.

**Comment by BLKSerene** [comment]
Thanks for the clarification, I got it.
