### ISSUE TITLE
How to initialize the tokenizer without the POS tagging feature?

### ISSUE THREAD

**Issue by BLKSerene** [Esukhia/pybo#35]
The doc gives examples on how to initialize the tokenizer together with part-of-speech capability, but how to initialize the tokenizer without the POS-tagging feature? And will there be any improvement of the speed of the tokenizer?

**Comment by drupchen** [comment]
As for the speed of the tokenizer, I think it is fairly reasonable. The last time I timed it, it was at about 50ms per token. What takes time is loading the trie into memory. Did you try instanciating once the tokenizer, then using it over and over again to tokenize different strings?

**Comment by drupchen** [comment]
As for the POS-tagging feature, what is currently done should not have any impact on the tokenizing speed. The only thing that is done is copy the POS tag found in the trie in the current Token object. 

For that reason, the POS tagging of pybo is not to be relied on and I don't advertise it because it doesn't deal at all with ambiguities like "I like to change/VERB my shoes." and "The change/NOUN of government (...)".

Having said that, there are a few things that I would like to change in pybo, and one of them is to strip down to a minimum the default options of the tokenizer, and then expose options such as including or not the POS-tagging. I don't think it will make any significant difference in terms of speed, but it makes things neater.

**Comment by BLKSerene** [comment]
Thanks. Answered in #34, so close this.
