### ISSUE TITLE
Failed to tokenize text with pybo 0.6.3

### ISSUE THREAD

**Issue by BLKSerene** [Esukhia/pybo#54]
Hi, after I've upgrade pybo to 0.6.3, it seems that the tokenizer does not work anymore.

```
>>> import pybo
>>> tok = pybo.WordTokenizer('POS')
Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    tok = pybo.WordTokenizer('POS')
  File "D:\Python\lib\site-packages\pybo\tokenizers\wordtokenizer.py", line 33, in __init__
    main, custom = config.get_tok_data_paths(profile, modifs=modifs, mode=mode)
  File "D:\Python\lib\site-packages\pybo\config.py", line 86, in get_tok_data_paths
    files = self.config['tokenizers']['profiles'][profile]
KeyError: 'tokenizers'
```

I've also noticed that there are some API changes, it is okay for me to just change `BoTokenizer `to `WordTokenizer`?

Also, I'm quite interested in the new Tibetan sentence and paragraph tokenizer (isn't every single line of text a paragraph in Tibetan?).

**Comment by drupchen** [comment]
I don't seem to get this issue. See bolow for what I get.

It looks like it is related to Windows? How could I help you solve that, since I don't have Windows?
The names of the Token attributes should look more natural. I have added an `entries` attribute that contains all existing words that share the same spelling (surface form/inflected form).
For example, the Token of `ཏུ་` has three possible interpretations, from the data included in pybo: 
```
pos: ADP, affixed: False, lemma: ཏུ་ | 
pos: SCONJ, affixed: False, lemma: ཏུ་ | 
lemma: ལ་, pos: PART, affixed: False |
```

Changing `BoTokenizer` to `WordTokenizer` should be fine 
searching for pybo refs in Wordless, I found [this line](https://github.com/BLKSerene/Wordless/blob/9bc9a5f3c40cdcba32e9fd75e3bd5d5170fd5060/src/wordless_text/wordless_text_processing.py#L292) where you will want to change `token.content` to `token.text`.

As for the sentence and paragraph tokenizers, They are the code we were talking about in the other issue, but adapted for the new release and integrated in what I called Text objects.
What you'll want to know is that tokenizing in sentences is more expensive than tokenizing in words since sentence_tokenizer() operates on a list of tokens generated by WordTokenizer. 
See [here](https://github.com/Esukhia/pybo/blob/master/tests/test_sent_par_tokenizer.py) for how you could use them. Both of their outputs is a list of tuples each containing `(<len of sent or par>, <list of tokens>)`.

If you want to have an idea of how it does it, check [this](https://github.com/Esukhia/pybo/blob/master/pybo/tokenizers/sentencetokenizer.py#L28-L57). You can't really rely on it 100%, but that's a good start. I would say it's a beta functionality. Sometimes, the sentences are split, sometimes two sentences end up in one block, but it makes for a good start and I am not aware of anything better for the moment. Better results will be acheived when the heuristics implemented will be improved and refined.

```
drupchen@drupchen-Inspiron-5558:~$ python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pybo
>>> tok = pybo.WordTokenizer('POS')
Building Trie... (...)
(18 s.)
>>> tokens = tok.tokenize('བཀྲ་ཤིས་བདེ་ལེགས་ཕུན་སུམ་ཚོགས། །རྟག་ཏུ་བདེ་བ་ཐོབ་པར་ཤོག')

>>> print([t.text for t in tokens])
['བཀྲ་ཤིས་', 'བདེ་ལེགས་', 'ཕུན་སུམ་', 'ཚོགས', '། །', 'རྟག་', 'ཏུ་', 'བདེ་བ་', 'ཐོབ་པ', 'ར་', 'ཤོག']

>>> tokens
[text: "བཀྲ་ཤིས་"
text_cleaned: "བཀྲ་ཤིས་"
text_unaffixed: "བཀྲ་ཤིས་"
syls: ["བཀྲ", "ཤིས"]
pos: NOUN
lemma: བཀྲ་ཤིས་
entries: | pos: NOUN, affixed: False, lemma: བཀྲ་ཤིས་ |
char_types: |CONS|CONS|SUB_CONS|TSEK|CONS|VOW|CONS|TSEK|
chunk_type: TEXT
syls_idx: [[0, 1, 2], [4, 5, 6]]
start: 0
len: 8

, text: "བདེ་ལེགས་"
text_cleaned: "བདེ་ལེགས་"
text_unaffixed: "བདེ་ལེགས་"
syls: ["བདེ", "ལེགས"]
pos: NOUN
lemma: བདེ་ལེགས་
entries: | pos: NOUN, affixed: False, lemma: བདེ་ལེགས་ |
char_types: |CONS|CONS|VOW|TSEK|CONS|VOW|CONS|CONS|TSEK|
chunk_type: TEXT
syls_idx: [[0, 1, 2], [4, 5, 6, 7]]
start: 8
len: 9

, text: "ཕུན་སུམ་"
text_cleaned: "ཕུན་སུམ་"
text_unaffixed: "ཕུན་སུམ་"
syls: ["ཕུན", "སུམ"]
pos: OTHER
lemma: ཕུན་སུམ་
entries: | pos: OTHER, affixed: False, lemma: ཕུན་སུམ་ |
char_types: |CONS|VOW|CONS|TSEK|CONS|VOW|CONS|TSEK|
chunk_type: TEXT
syls_idx: [[0, 1, 2], [4, 5, 6]]
start: 17
len: 8

, text: "ཚོགས"
text_cleaned: "ཚོགས་"
text_unaffixed: "ཚོགས་"
syls: ["ཚོགས"]
pos: NOUN
lemma: ཚོགས་
entries: | pos: NOUN, affixed: False, lemma: ཚོགས་ |
char_types: |CONS|VOW|CONS|CONS|
chunk_type: TEXT
syls_idx: [[0, 1, 2, 3]]
start: 25
len: 4

, text: "། །"
char_types: |NORMAL_PUNCT|TRANSPARENT|NORMAL_PUNCT|
chunk_type: PUNCT
start: 29
len: 3

, text: "རྟག་"
text_cleaned: "རྟག་"
text_unaffixed: "རྟག་"
syls: ["རྟག"]
pos: VERB
lemma: རྟག་
entries: | pos: VERB, affixed: False, lemma: རྟག་ |
char_types: |CONS|SUB_CONS|CONS|TSEK|
chunk_type: TEXT
syls_idx: [[0, 1, 2]]
start: 32
len: 4

, text: "ཏུ་"
text_cleaned: "ཏུ་"
text_unaffixed: "ཏུ་"
syls: ["ཏུ"]
pos: ADP
lemma: ཏུ་
entries: | pos: ADP, affixed: False, lemma: ཏུ་ | pos: SCONJ, affixed: False, lemma: ཏུ་ | lemma: ལ་, pos: PART, affixed: False |
char_types: |CONS|VOW|TSEK|
chunk_type: TEXT
syls_idx: [[0, 1]]
start: 36
len: 3

, text: "བདེ་བ་"
text_cleaned: "བདེ་བ་"
text_unaffixed: "བདེ་བ་"
syls: ["བདེ", "བ"]
pos: VERB
lemma: བདེ་བ་
entries: | pos: VERB, affixed: False, lemma: བདེ་བ་ |
char_types: |CONS|CONS|VOW|TSEK|CONS|TSEK|
chunk_type: TEXT
syls_idx: [[0, 1, 2], [4]]
start: 39
len: 6

, text: "ཐོབ་པ"
text_cleaned: "ཐོབ་པ"
text_unaffixed: "ཐོབ་པ"
syls: ["ཐོབ", "པ"]
pos: VERB
lemma: ཐོབ་པ་
entries: | pos: VERB, affixed: True, lemma: ཐོབ་པ་ |
char_types: |CONS|VOW|CONS|TSEK|CONS|
chunk_type: TEXT
affix_host: True
syls_idx: [[0, 1, 2], [4]]
start: 45
len: 5

, text: "ར་"
text_cleaned: "ར་"
text_unaffixed: "ར་"
syls: ["ར"]
pos: PART
lemma: ལ་
entries: | lemma: ལ་ |
char_types: |CONS|TSEK|
chunk_type: TEXT
affix: True
syls_idx: [[0]]
start: 50
len: 2

, text: "ཤོག"
text_cleaned: "ཤོག་"
text_unaffixed: "ཤོག་"
syls: ["ཤོག"]
pos: VERB
lemma: ཤོག་
entries: | pos: VERB, affixed: False, lemma: ཤོག་ |
char_types: |CONS|VOW|CONS|
chunk_type: TEXT
syls_idx: [[0, 1, 2]]
start: 52
len: 3

]
>>> 

```
where (...) is lots of unwanted prints, but that's a bug I am trying to solve.

**Comment by BLKSerene** [comment]
OK, I found where the problem lies. There's an older version of the file "pybo.yaml", removing this file and letting pybo create a new one solved the problem

**Comment by drupchen** [comment]
I wonder how this didn't come to my mind... It always happens to me. Great
that it is solved!!!
